name: Semver
on:
  workflow_dispatch:

jobs:
  read-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package.outputs.prop }}
      next-major: ${{ steps.semvers.outputs.major }}
      next-minor: ${{ steps.semvers.outputs.minor }}
      next-patch: ${{ steps.semvers.outputs.patch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: notiz-dev/github-action-json-property@v0.2.0
        id: package
        with:
          path: package.json
          prop_path: "version"
      - name: 'Get next semver'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ needs.read-version.outputs.version }}
      - run: echo 'Version = @ ${{ steps.package.outputs.prop }}'
      - run: echo 'Next major = @ ${{ steps.semvers.outputs.major }}'
      - run: echo 'Next minor = @ ${{ steps.semvers.outputs.minor }}'
      - run: echo 'Next patch = @ ${{ steps.semvers.outputs.patch }}'
